apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudapp
  name: cloudappservice 
spec:
  type: NodePort
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 5000
  selector:
    app: cloudapp
