apiVersion: apps/v1
kind: Deployment
metadata: 
  name: testappv57
  labels: 
    app: cloudapp
spec: 
  replicas: 3
  selector: 
    matchLabels:
       app: cloudapp
  template: 
    metadata:
       labels:
          app: cloudapp
    spec:
       containers:
       - name: testappv57
         image: ranjik/testrepository:testappv57
         ports:
         - containerPort: 5000
       #imagePullSecrets:
       #- name: testappv57
