apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nativecloudapp:40
  labels: 
    app: cloudapp
spec: 
  replicas: 3
  selector: 
    matchLabels:
       app: cloudapp
  template: 
    metadata:
       labels:
          app: cloudapp
    spec:
       containers:
       - name: nativecloudapp:40
         image: ranjik/test:nativecloudappv40
         ports:
         - containerPort: 5000
       imagePullSecrets:
       - name: nativecloudapp:40
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudapp
  name: nativecloudapp:40
spec:
  type: NodePort
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 5000
  selector:
    app: cloudapp
