apiVersion: apps/v1
kind: Deployment
metadata: 
  name: v1
  labels: 
    app: cloudapp
spec: 
  replicas: 3
  selector: 
    matchLabels:
       app: cloudapp
  template: 
    metadata:
       labels:
          app: cloudapp
    spec:
       containers:
       - name: v1
         image: ranjik/testrepository:v1
         ports:
         - containerPort: 5000
       #imagePullSecrets:
       #- name: v1
