apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nativecloudappv46
  labels: 
    app: cloudapp
spec: 
  replicas: 3
  selector: 
    matchLabels:
       app: cloudapp
  template: 
    metadata:
       labels:
          app: cloudapp
    spec:
       containers:
       - name: nativecloudappv46
         image: ranjik/testrepository:nativecloudappv46
         ports:
         - containerPort: 5000
       #imagePullSecrets:
       #- name: regcred1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudapp
  name: nativecloudappv46
spec:
  type: NodePort
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 5000
  selector:
    app: cloudapp
